### PR TITLE
Updates to create proper NPM module

### PR DESCRIPTION
**Pull request by nickrnet**
https://www.npmjs.com/package/@networkcobwebs/minecraft-server-manager

### CODE REVIEW

**Comment by nickrnet** [comment]
@DevBonBon Can you tell me if this works in your environment?

**Comment by fluvf** [comment]
It works, but using the users home directory seems like bad practice, especially on windows
~The directory should rather be configurable, probably through the current `api.properties`~ Never mind, i completely forgot that it already is through `server.properties`
I still think those should be `.json` files tho

**Comment by nickrnet** [comment]
Ok, I'll merge this so it matches the NPM site and we can further discuss the location in another PR.

**Comment by nickrnet** [comment]
I created a GitHub organization to match the NPM organization and will be moving this repo there over the weekend. According to GH, you shouldn't see a change other than changing the remote, I'll provide directions if needed. I also have a Slack for networkcobwebs as well, we can see how that works if we want. Might be useful for you to PR your email address in the top-level `package.json` file so I can add you to the org if we need to, but only if you want to. But one of those might be better than communicating only via PR 😉In general, I treat Slack as asynchronous communication like email anyway - I have most notifications disabled but use it to go back and catch up when I have time (like how I use Twitter). Up to you though.

Anyway, moving to the org might be easier to split the web ui from the server/api code as well. That was the thought anyway.

**Pull request merged**
