### PR TITLE
Package: Replace custom eslint with semistandard

### PR DESCRIPTION
**Pull request by fluvf**
I feel like the [semistandard](https://www.npmjs.com/package/semistandard) (and the [standard](https://github.com/standard/standard#why-should-i-use-javascript-standard-style)) package is a good fit to the coding style of this project, and as it's a well maintained project, it'll lift the need to worry about maintaining eslint.
Also includes a fix for the `npm run *` commands

### CODE REVIEW

**Review by nickrnet — CHANGES_REQUESTED** [review]
- The `.nvmrc` file needs to stay. Or, provide another means of handling NodeJS versions and minimum requirements that isn't just "rely on this version".
- The `.vscode` directory needs to stay. It has all of the run/debug configurations for debugging. Or, provide another means of IDE debugging.
- The `build` directory needs to stay as the MinecraftAPI serves it via ExpressJS. It contains the production build of the React app. Typically I agree with you on this point, but until some kind of build process is running, this is what we have.

I don't care about 2 vs 4 spaces or quotes, so that much is fine, and if it's easier to manage, even better. Can you include a link to the semistandard configuration in this PR before it's merged?

**Comment by fluvf** [comment]
- I'll add the [engines](https://docs.npmjs.com/files/package.json#engines) field to `package.json`, to partially enforce a minimum NodeJS version. Keeping the readme updated with a `Requirements` part should also help.
- I had the impression that the `.vscode` folder holds workspace specific configurations files. And unless the agreed upon editor for the entire project is VSCode I don't think it should be included in the source.
- I'll remove the build directory from `.gitignore`. There probably should be an issue added for replacing it with a build process later on

**Comment by fluvf** [comment]
Rebased and addressed your comments.
Do you think the banner that was added in 7b1e18a is a good enough note about the coding rules?

**Comment by fluvf** [comment]
Ok, I did some more research about the `.vscode` folder and changed my opinion about removing it. Sorry this has been a bit of a process :D 

I think only two files should be allowed in there, `extensions.json` and `tasks.json`. But instead of removing `launch.json` and `settings.json` a `.default` suffix would be added onto them.
I don't think enforcing workspace settings onto others is a good idea, but I can see how the file exclusions would be necessary for the time being.
I'd also think most have / want to have their own debugging commands, but offering sensible defaults might give an easier start.

But as this is a bit of an opinionated pull request, I split it into three parts:
- #40 with the general .gitignore cleaning
- #41 with the proposed .vscode folder changes (based on #40 )
- and this pr with the `semistandard` changes

**Comment by fluvf** [comment]
Did another rebase

**Comment by fluvf** [comment]
Rebased

**Comment by fluvf** [comment]
Getting this merged would be great, as it would automate much of my workflow

(also I will keep rebasing this until you either merge it or say no)

**Review by nickrnet — APPROVED** [review]

**Comment by fluvf** [comment]
Thanks!

**Pull request merged**
