### PR TITLE
 Server: Grab java home path from 'java -XshowSettings:properties'

### PR DESCRIPTION
**Pull request by fluvf**
As far as I could tell the Mac(?) version of the check already depended on a proper java installation, so assuming `java` can be found in `PATH` should be sane.
With that assumption the check might seem a bit redundant, but it can be used in the future if / when custom java executables are supported to quickly get the default one.

### CODE REVIEW

**Review by nickrnet — CHANGES_REQUESTED** [review]
Thanks for the PR. A couple of notes in general:

- Please include the source files of the jar `java_home.jar` in the PR for review. 
- Having the JAVA_HOME be its own property is useful, so I would rename the `javaPath` property to `javaExecutable` or something similar that holds the combined `javaHome + /bin/java` path. I am not against long variable names as long as they make sense.

Thanks for fixing the missing callback bug!

**Comment by fluvf** [comment]
The `java_home.jar` is really simple, only containing the following code, which has been shrunk and obfuscated using ProGuard:
```
public static void main(String[] args) {
  System.out.print(System.getProperty("java.home"));
}
```
I feel like adding the source files for that into this project is a bit redundant, that's why I only left a note about it in the commit message. But if you feel like it's absolutely necessary, I'll add them.

How would you feel about having `javaPath` and `javaHome`? I'll add that once I get your confirmation about the .jar source

**Comment by fluvf** [comment]
@nickrnet Could you take another look at this? It's rather hard to test things without the java check working :D
I'll add the source files if you feel like the commit message isn't enough, but I think another form of documentation would be better. Maybe add something to /docs about it?
I could also write something to get it from the output of `java -version`, but that's more prone to bugs and harder to maintain.

**Comment by nickrnet** [comment]
My biggest concern here was having executable binary packages without the source. I know there are already some things like this installed by npm, but don't want to run into trouble from people that run this with packages we are blind to.

I know the commercial Minecraft package has a JRE bundled (i.e. their Launcher), so I'm investigating options there as well.

Can you walk me through the testing that has been done on this change? Yes, a `java.md` file in `doc` with this explanation (and maybe a checksum of the jar) would probably be sufficient for now to get moving.

**Comment by fluvf** [comment]
Finally found a javascript only solution!
The check now grabs the home directory from `-XshowSettings:properties`, which is a 'Non-standard' option. According to the documentation, "Non-standard options are general purpose options that are specific to the Java HotSpot Virtual Machine, so they are not guaranteed to be supported by all JVM implementations, and are subject to change."
Reading through the docs, the setting is still present in versions [8](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html#BABHDABI), [9](https://docs.oracle.com/javase/9/tools/java.htm#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE__BABHDABI), [10](https://docs.oracle.com/javase/10/tools/java.htm#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE__BABHDABI), [11](https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE) and [12](https://docs.oracle.com/en/java/javase/12/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE), which should be enough for us.
I'm also assuming that the option is present in all builds of java, be it from Oracle or not.

As far as testing goes, I run the functions and then the whole script on both my windows and ubuntu machines, with Oracles 1.8 and OpenJDKs 11 java versions respectively.

**Comment by nickrnet** [comment]
Sweet, this works on OS X too. Nice!

**Pull request merged**
